// Pictures for the skill-check rooms and the trivia sphinx, shown beside the room title.
// Same approach as sprites.js: 16x16 pixel maps, '.' is transparent. Each picture gets
// a soft outline so dark pixels still read on the dark event panel.

export const PIC_PAL = {
  K: 0x1a1a22, W: 0xf4f4f4, G: 0x8a8f99, g: 0x4a4f5a, B: 0x8a5a36, b: 0x5a3b22,
  Y: 0xf2b441, R: 0xd2463c, U: 0x3a78c8, u: 0x9fc3e8, N: 0x6cc46f, n: 0x2f6b3a,
  S: 0xf0c8a0, T: 0xd8c49a, C: 0xefe3c2, L: 0x5b5278, P: 0xa57be0, O: 0x6e6e84,
};

export const PICTURES = {
  // A half-finished sudoku with one wrong 7, in red pen.
  sudoku: [
    '................',
    '.ggggggggggggg..',
    '.gCCCgCCCgCCCg..',
    '.gCKCgCCCgCRCg..',
    '.gCCCgCCCgCCCg..',
    '.ggggggggggggg..',
    '.gCCCgCCCgCCCg..',
    '.gCCCgCKCgCCCg..',
    '.gCCCgCCCgCCCg..',
    '.ggggggggggggg..',
    '.gCCCgCCCgCCCg..',
    '.gCKCgCCCgCKCg..',
    '.gCCCgCCCgCCCg..',
    '.ggggggggggggg..',
  ],
  // The bridge troll, tusks and all, over a plank bridge.
  troll: [
    '................',
    '....nnnnnnnn....',
    '...nNNNNNNNNn...',
    '..nNNNNNNNNNNn..',
    '..nNNKNNNNKNNn..',
    '.nnNNNNNNNNNNnn.',
    '.nNNNNNNNNNNNNn.',
    '..nNNNNnnNNNNn..',
    '..nNNNNNNNNNNn..',
    '..nNWKKKKKKWNn..',
    '..nNWKKKKKKWNn..',
    '...nNNNNNNNNn...',
    '....nnnnnnnn....',
    '..bbbbbbbbbbbb..',
    '..b..b....b..b..',
  ],
  // A stone tablet covered in runes (or a grocery list).
  inscription: [
    '................',
    '....LLLLLLLL....',
    '...LLLLLLLLLL...',
    '..LLCLCCLLCLLL..',
    '..LLCLLCLCCLLL..',
    '..LLLLLLLLLLLL..',
    '..LLCCLLCLCLLL..',
    '..LLLCLCCLLLLL..',
    '..LLLLLLLLLLLL..',
    '..LLCLCLLCCLLL..',
    '..LLCCLLCLCLLL..',
    '..LLLLLLLLLLLL..',
    '..LLLLLLLLLLLL..',
    '.gggggggggggggg.',
  ],
  // Two cliff edges and a rope hanging down the far side.
  chasm: [
    '................',
    '................',
    '................',
    '...........B....',
    '.........TTB....',
    'NNNNNN...TNNNNNN',
    'GGGGGG...TGGGGGG',
    'GGGGGgK..TgGGGGG',
    'GGGGgKKK.TKgGGGG',
    'GGGGgKKKKTKgGGGG',
    'GGGgKKKKKTKKgGGG',
    'GGGgKKKKKKKKgGGG',
    'GGgKKKKKKKKKKgGG',
    'GGgKKKKKKKKKKgGG',
    'GgKKKKKKKKKKKKgG',
  ],
  // A padlock built out of plastic bricks.
  bricks: [
    '................',
    '.....YYYYYY.....',
    '....YY....YY....',
    '....Y......Y....',
    '....Y......Y....',
    '..R.R.R.U.U.U...',
    '..RRRRRRUUUUUU..',
    '..RRRRRRUUUUUU..',
    '..NNNNYYYYYYNN..',
    '..NNNNYKKYYYNN..',
    '..UUUUUKKRRRRR..',
    '..UUUUUURRRRRR..',
    '..NNNNNNNNNNNN..',
    '..NNNNNNNNNNNN..',
  ],
  // A mountain with a zigzag trail up the side.
  switchback: [
    '.......W........',
    '......WGW.......',
    '.....GGGGG......',
    '....GTTTTTG.....',
    '....GGGGGTGG....',
    '...GGTTTTTGGG...',
    '...GGTGGGGGGG...',
    '..GGGTTTTTTGGG..',
    '..GGGGGGGGTGGGG.',
    '.GGGGTTTTTTGGGG.',
    '.GGGGTGGGGGGGGGG',
    'GGGGGTTTTTTTGGGG',
    'GGGGGGGGGGGTGGGG',
    'gggggggggggTgggg',
    'gggggggggggggggg',
  ],
  // A bookshelf of very long nonfiction.
  library: [
    '................',
    '.bbbbbbbbbbbbbb.',
    '.bRUNYRPUbNRYUb.',
    '.bRUNYRPUbNRYUb.',
    '.bRUNYRPUbNRYUb.',
    '.bbbbbbbbbbbbbb.',
    '.bUYRbNPURYNUbb.',
    '.bUYRbNPURYNUbb.',
    '.bUYRbNPURYNUbb.',
    '.bbbbbbbbbbbbbb.',
    '.bNRUPYRbUNYRUb.',
    '.bNRUPYRbUNYRUb.',
    '.bNRUPYRbUNYRUb.',
    '.bbbbbbbbbbbbbb.',
    '.b............b.',
  ],
  // The goblin's pitch deck on an easel: up and to the right.
  pitch: [
    '................',
    '.GGGGGGGGGGGGG..',
    '.GWWWWWWWWWWWG..',
    '.GWWWWWWWWWNWG..',
    '.GWWWWWWWWNWWG..',
    '.GWWWWWWWNWWWG..',
    '.GWWWWWWNWWWWG..',
    '.GWWNWWNWWWWWG..',
    '.GWNWNNWWWWWWG..',
    '.GWWWWWWWWWWWG..',
    '.GGGGGGGGGGGGG..',
    '.....b..b.......',
    '....b....b......',
    '...b......b.....',
    '..b........b....',
  ],
  // An open hand, mid-slap.
  slapbet: [
    '................',
    '......S.S.......',
    '....S.S.S.S.....',
    '....S.S.S.S.....',
    '....SSSSSSS.....',
    '..S.SSSSSSS.....',
    '..SSSSSSSSS.....',
    '...SSSSSSSS..W..',
    '....SSSSSSS.W...',
    '.....SSSSS..WW..',
    '.....SSSSS......',
    '.....RRRRR......',
    '.....RRRRR......',
  ],
  // A clipboard with the draft rankings.
  draft: [
    '.....gGGg.......',
    '..bbbbGGbbbbb...',
    '..bWWWWWWWWWb...',
    '..bWKWKKKKWWb...',
    '..bWWWWWWWWWb...',
    '..bWKWKKKKKWb...',
    '..bWWWWWWWWWb...',
    '..bWKWKKKWWWb...',
    '..bWWWWWWWWWb...',
    '..bWRWKKKKWWb...',
    '..bWWWWWWWWWb...',
    '..bWNWKKKKKWb...',
    '..bWWWWWWWWWb...',
    '..bbbbbbbbbbb...',
  ],
  // A ledger grid with one cell in the red.
  spreadsheet: [
    '................',
    '.nnnnnnnnnnnnnn.',
    '.nWWWnWWWWnWWWn.',
    '.nnnnnnnnnnnnnn.',
    '.nWWWnWWWWnWWWn.',
    '.nnnnnnnnnnnnnn.',
    '.nWWWnWWWWnRRRn.',
    '.nnnnnnnnnnnnnn.',
    '.nWWWnWWWWnWWWn.',
    '.nnnnnnnnnnnnnn.',
    '.nWWWnWWWWnWWWn.',
    '.nnnnnnnnnnnnnn.',
  ],
  // A stone fountain full of something green and glowing.
  fountain: [
    '.......u........',
    '......u.u.......',
    '.....u.N.u......',
    '.......N........',
    '......NNN.......',
    '.......G........',
    '.......G........',
    '..GGGGGGGGGGGG..',
    '..GNNNNNNNNNNG..',
    '..GNNuNNNNuNNG..',
    '..GGGGGGGGGGGG..',
    '...gGGGGGGGGg...',
    '....gGGGGGGg....',
    '....gggggggg....',
  ],
  // A maple-leaf flag over a border booth.
  border: [
    '................',
    '..KRRRWWWWWRRR..',
    '..KRRRWWRWWRRR..',
    '..KRRRWRRRWRRR..',
    '..KRRRWWRWWRRR..',
    '..KRRRWWWWWRRR..',
    '..K.............',
    '..K...gggggggg..',
    '..K...gUUUUUUg..',
    '..K...gTuuuuTg..',
    '..K...gTuuuuTg..',
    '..K...gTTTTTTg..',
    '..K...gTTTTTTg..',
    '.gggggggggggggg.',
  ],
  // Moving boxes, stacked.
  boxes: [
    '................',
    '....bbbbbbbb....',
    '....bBBBTBBb....',
    '....bBKKTBBb....',
    '....bBBBTBBb....',
    '....bbbbbbbb....',
    '.bbbbbbbbbbbbbb.',
    '.bBBTBBbbBBTBBb.',
    '.bBBTBBbbBBTBBb.',
    '.bBBTBBbbBBTBBb.',
    '.bBBTBBbbBBTBBb.',
    '.bbbbbbbbbbbbbb.',
  ],
  // A black diamond trail sign in the snow.
  blackdiamond: [
    '..gggggggggggg..',
    '..gWWWWKWWWWWg..',
    '..gWWWKKKWWWWg..',
    '..gWWKKKKKWWWg..',
    '..gWKKKKKKKWWg..',
    '..gWWKKKKKWWWg..',
    '..gWWWKKKWWWWg..',
    '..gWWWWKWWWWWg..',
    '..gggggggggggg..',
    '.......b........',
    '.......b........',
    '.......b........',
    '.......b........',
    '..uWWWWbWWWWWu..',
    '.uWWWWWWWWWWWWu.',
  ],
  // The Pub Trivia Sphinx.
  sphinx: [
    '................',
    '.....YYYYYY.....',
    '....YUYYYYUY....',
    '...YUYSSSSYUY...',
    '...YUSKSSKSUY...',
    '...YUSSSSSSUY...',
    '...YUSSRRSSUY...',
    '....YSSSSSSY....',
    '.....TTTTTT.....',
    '....TTTTTTTTT...',
    '...TTTTTTTTTTT..',
    '..TTTTTTTTTTTTT.',
    '..TT.TT...TTTTT.',
    '..TTTTT...TTTTT.',
  ],
};

// Pad every picture to 16x16, bottom-aligned, so hand-drawn maps can be shorter.
export function normalized(rows) {
  const w = 16, h = 16;
  const padded = rows.map((r) => r.padEnd(w, '.').slice(0, w));
  while (padded.length < h) padded.unshift('.'.repeat(w));
  return padded.slice(-h);
}

export const picKey = (id) => `pic-${id}`;
